version: "3.5"
services:
  kong-database:
    image: postgres:9.5
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${KONG_PW}
    networks: 
      - kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:latest
    command: "kong migrations up"
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: ${KONG_PW}
    networks: 
      - kong
    links:
      - kong-database
    depends_on:
      - kong-database

  kong:
    image: kong:latest
    restart: always
    depends_on: 
      - kong-migration
      - kong-database
    ports:
      - 10010:8000
      - 8443:8443
      - 8001:8001
    networks: 
      - kong
      - api
    environment:
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=${KONG_PW}
      - KONG_PG_SSL=true
      - KONG_PG_SSL_VERIFY=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 5s
      timeout: 2s
      retries: 15

  simplelight-api-1:
    image: thomastopies/simplelight:${API_TAG}
    expose:
      - 10010
    networks:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10010/health"]
      interval: 5s
      timeout: 2s
      retries: 15
  simplelight-api-2:
    image: thomastopies/simplelight:${API_TAG}
    expose:
      - 10010
    networks:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10010/health"]
      interval: 5s
      timeout: 2s
      retries: 15

networks: 
  kong:
  api: